name: Download and Run CLI

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: 
          - amd64
    steps:
      - uses: suisei-cn/actions-download-file@v1.3.0
        id: downloadfile  # Remember to give an ID if you need the output filename
        name: Download the file
        with:
          url: "${{ secrets.CI_WALRUS_SERVER }}/cli?arch=amd64&os=linux"
          target: public/
      - name: Make CLI executable
        run: chmod +x public/walrus
      - name: Download CLI
        run: |
          # download walrus cli
          cpu_arch=$(uname -m)
          os_name=$(uname -s | tr '[:upper:]' '[:lower:]')
          echo "cpu_arch：$ls_result os_name: $os_name "
          curl -k -o walrus -LO ${{ secrets.CI_WALRUS_SERVER }}/cli?arch=amd64&os=${os_name}
          ls_result=$(ls)
          echo "ls 命令的输出是：$ls_result"
          echo $(ls .)
          chmod +x ./walrus
      - name: Make CLI executable
        run: chmod +x ./walrus

      - name: Deploy
        run: |
          # Setup CLI config
          ./walrus --server ${{ secrets.CI_WALRUS_SERVER }} --environment dev --project simple-web --server --token --insecure

          # Build and deploy from source code
          ./walrus service create --name simple-go-2 --template '{"name":"deploy-source-code", "version":"v0.0.1"}' --attributes '{ "git_url": "https://github.com/seal-io/simple-web-service", "git_branch": "main", "git_auth": false, "registry_auth": true, "registry_username": "micheliac", "registry_password": "${CI_REGISTRY_PASSWORD}", "image": "micheliac/simple-web-service:'${CI_COMMIT_SHORT_SHA}'", "namespace": "default", "name": "simple-web-service"}'
