name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: 
          - amd64
    steps:
      - name: Download CLI
        run: |
          # Download walrus cli
          curl -v -k -o walrus -LO "${{ secrets.CI_WALRUS_SERVER }}/cli?arch=amd64&os=linux"
          chmod +x ./walrus

      - name: Deploy
        run: |
          # Setup CLI config
          ./walrus config setup --server ${{ secrets.CI_WALRUS_SERVER }} --project web --environment dev --token ${{ secrets.CI_WALRUS_TOKEN }} --insecure

          # Build and deploy from source code
          ./walrus service create --name simple-web-service --template '{"name":"deploy-source-code", "version":"v0.0.1"}' --attributes '{ "git_url": "https://github.com/seal-io/simple-web-service", "git_branch": "main", "git_auth": false, "registry_auth": true, "registry_username": "micheliac", "registry_password": "${{ secrets.CI_REGISTRY_PASSWORD }}", "image": "micheliac/simple-web-service:${{ github.sha }}", "namespace": "default", "name": "simple-web-service"}' -d
